Traceback (most recent call last):
  File "/data3/gc/SeLM_v2/src/cte_speedup.py", line 339, in train_epoch
    selected_locs, loss_cos, loss_cro, loss_tot = self.loom(
  File "/data3/gc/SeLM_v2/src/cte_speedup.py", line 273, in loom
    loss_cos, loss_cro, loss_tot = self.calc_loss(
  File "/data3/gc/SeLM_v2/src/cte_speedup.py", line 107, in calc_loss
    loss_cos, loss_cro, loss_tot = compute_weighted_loss(
  File "/data3/gc/SeLM_v2/src/loss.py", line 143, in compute_weighted_loss
    loss_cos = torch.square(ct_val_cos - eu_val_cos)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.79 GiB. GPU 1 has a total capacity of 23.69 GiB of which 6.79 GiB is free. Including non-PyTorch memory, this process has 16.88 GiB memory in use. Of the allocated memory 16.55 GiB is allocated by PyTorch, and 21.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
