Traceback (most recent call last):
  File "/data3/gc/SeLM_v2/src/utils.py", line 1341, in wrapper
    return func(*args, **kwargs)
  File "/data3/gc/SeLM_v2/src/cte.py", line 549, in train_epoch
    self.train_vocab_blocks(sid)
  File "/data3/gc/SeLM_v2/src/cte.py", line 462, in train_vocab_blocks
    loss  = self.loom_vocab(
  File "/data3/gc/SeLM_v2/src/cte.py", line 228, in loom_vocab
    cos_nei_cnc = self.cos_similarity(pos_loc[:, None, None, :], cnc_loc[None, :, :, :])
  File "/data3/gc/SeLM_v2/src/cte.py", line 140, in cos_similarity
    return sg * (1 - s)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.92 GiB. GPU 2 has a total capacity of 23.69 GiB of which 520.06 MiB is free. Including non-PyTorch memory, this process has 13.77 GiB memory in use. Process 2686361 has 6.13 GiB memory in use. Process 2686362 has 3.26 GiB memory in use. Of the allocated memory 12.52 GiB is allocated by PyTorch, and 979.28 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
