Traceback (most recent call last):
Traceback (most recent call last):
  File "/data3/gc/SeLM_v2/src/utils.py", line 1341, in wrapper
    return func(*args, **kwargs)
  File "/data3/gc/SeLM_v2/src/utils.py", line 1341, in wrapper
    return func(*args, **kwargs)
  File "/data3/gc/SeLM_v2/src/cte.py", line 549, in train_epoch
    self.train_vocab_blocks(sid)
  File "/data3/gc/SeLM_v2/src/cte.py", line 549, in train_epoch
    self.train_vocab_blocks(sid)
  File "/data3/gc/SeLM_v2/src/cte.py", line 462, in train_vocab_blocks
    loss  = self.loom_vocab(
  File "/data3/gc/SeLM_v2/src/cte.py", line 228, in loom_vocab
    cos_nei_cnc = self.cos_similarity(pos_loc[:, None, None, :], cnc_loc[None, :, :, :])
  File "/data3/gc/SeLM_v2/src/cte.py", line 139, in cos_similarity
    s = exp.float() / self.h
  File "/data3/gc/SeLM_v2/src/cte.py", line 462, in train_vocab_blocks
    loss  = self.loom_vocab(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 986.00 MiB. GPU 5 has a total capacity of 23.69 GiB of which 205.12 MiB is free. Including non-PyTorch memory, this process has 6.10 GiB memory in use. Process 2686359 has 7.98 GiB memory in use. Process 2686361 has 6.13 GiB memory in use. Process 2686362 has 3.26 GiB memory in use. Of the allocated memory 5.30 GiB is allocated by PyTorch, and 509.15 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
